# action 的名称
name: Deploy GitHub Pages - Press UI

# 触发条件：在 push 到 main 分支后
on:
  push:
    branches:
      - feature/archive

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install Dependencies
        run: pnpm install

      # 生成静态文件
      - name: Build
        # error:0308010C:digital envelope routines::unsupported
        # https://blog.csdn.net/zch981964/article/details/131689132
        run: npm run init && export NODE_OPTIONS=--openssl-legacy-provider && npm run docs:build && npm run build && cp -r dist/build/h5 docs/.vuepress/dist

      # 部署到 GitHub Pages
      - name: Deploy
        # 使用别人写好的一个 action
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # 打包后的文件部署到哪个分支上
          BRANCH: docs
          # 打包后的文件在哪里
          FOLDER: docs/.vuepress/dist
